import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NavBar from "./components/NavBar";
import { ThemeProvider } from "@/components/theme-provider";
import { AuthSessionProvider } from "../app/components/AuthSessionProvider";
import { PropertiesProvider } from "../app/context/PropertiesContext";
import PhoneNavBar from "./components/PhoneNavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthSessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <PropertiesProvider>
             
              <NavBar />
               <div className="pb-[70px] lg:pb-0"> 
              {children}
               </div>
              <Toaster />
              <PhoneNavBar/>
              
            </PropertiesProvider>
          </ThemeProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
